name: Deploy Node.js Services to AWS Lambda
 
on:
  push:
    branches:
      - workflow_dispatch
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Shift directory
        run: |
          cd NodeSample
          pwd
 
      - name: Install dependencies
        run: |
          cd ./NodeSample
          npm install
          
          
          
 
      - name: Package Node.js services
        run: zip -r package.zip .
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
 
      - name: Upload to S3
        run: aws s3 cp package.zip s3://${{ secrets.S3_BUCKET_NAME }}/package.zip
 
  update-lambda:
    needs: build-and-deploy
    runs-on: ubuntu-latest
 
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
 
      - name: Download package from S3
        run: aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/package.zip package.zip
 
      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://package.zip
